select *from ratings
WHERE student_id=$1;




-- USE THE FOLLOW QUERRY IF YOU DONT NEED TO SELECT EVERYTHING FROM THE TABLE. IN THIS CASE RATINGS TABLE HAS BUNCH OF COLUMNS BUT WE WANT ONLY SPECIFIC COLUMNS. TO GET THAT YOU USE TH FOLLOW QURRY. IF YOU NEED ALL COLOUMS THEN WE USE THE QUERRY ABOVE.

-- select users_id, attendance, comments from ratings
-- WHERE users_id=$1;